# Generated by Django 3.2.25 on 2024-06-01 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almondz_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensegroupmodel',
            name='total_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
