# Generated by Django 3.2.25 on 2024-06-01 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almondz_app', '0002_alter_expensegroupmodel_total_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expensegroupmodel',
            old_name='user',
            new_name='users',
        ),
    ]
