# Generated by Django 3.2.25 on 2024-06-01 18:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('almondz_app', '0003_rename_user_expensegroupmodel_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensetxnmodel',
            name='split_type',
        ),
        migrations.AddField(
            model_name='expensemodel',
            name='split_type',
            field=models.CharField(choices=[('EQUAL', 'Equal'), ('EXACT', 'Exact'), ('PERCENT', 'Percent')], default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
