# Generated by Django 3.2.25 on 2024-06-01 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almondz_app', '0004_auto_20240601_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensemodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='almondz_app.usermodel'),
        ),
    ]
