# Generated by Django 3.2.25 on 2024-06-01 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almondz_app', '0005_alter_expensemodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensegroupmodel',
            name='users',
            field=models.ManyToManyField(related_name='groups', to='almondz_app.UserModel'),
        ),
    ]
