# Generated by Django 3.2.25 on 2024-06-01 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almondz_app', '0007_auto_20240602_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensemodel',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='almondz_app.expensegroupmodel'),
        ),
    ]
