# Generated by Django 3.2.25 on 2024-06-01 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almondz_app', '0008_alter_expensemodel_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensemodel',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almondz_app.expensegroupmodel'),
        ),
        migrations.AlterField(
            model_name='expensemodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almondz_app.usermodel'),
        ),
        migrations.AlterField(
            model_name='expensetxnmodel',
            name='expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almondz_app.expensemodel'),
        ),
        migrations.AlterField(
            model_name='expensetxnmodel',
            name='owes_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owes_user', to='almondz_app.usermodel'),
        ),
        migrations.AlterField(
            model_name='expensetxnmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='almondz_app.usermodel'),
        ),
    ]
